### ISSUE TITLE
Get client IP address

### ISSUE THREAD

**Issue by ofilin86** [nathan-hoad/python-icap#4]
Hello,
how to get client IP address?

I set 
```
icap_enable on
icap_preview_enable off
icap_send_client_ip on
icap_send_client_username on
icap_service reqmod reqmod_precache bypass=0 icap://127.0.0.1:1334/reqmod
```
but I do not see the ip address anywhere
Thank you

**Comment by nathan-hoad** [comment]
Hello,

I'm not providing support for Squid. This is a question for the Squid mailing list.

Thank you,

Nathan.

**Comment by ofilin86** [comment]
Sorry for my English :) You misunderstood me, how to get the address in the python-icap? I configured a Squid to send an ip address to the icap server. But I do not know how to get the IP address in my program... I know for sure that Squid sends the IP address
