### ISSUE TITLE
Criteria not working

### ISSUE THREAD

**Issue by ofilin86** [nathan-hoad/python-icap#5]
Hello, Nathan
This criteria not working
`@handler(MethodCriteria('POST') & (ContentTypeCriteria('application/x-www-form-urlencoded') | ContentTypeCriteria('multipart/form-data') | ContentTypeCriteria('application/octet-stream')), raw=True)`
why? how to fix?

UPD: and may be remove this for work in reqmod?:
line 128-129 in criteria.py
```
if request.is_reqmod:
            return False

```
Thank you

**Comment by nathan-hoad** [comment]
Sure, that makes sense. If you submit a pull request for it, I'll merge it in.
