### ISSUE TITLE
Ordering query params. Problem

### ISSUE THREAD

**Issue by ghost** [nathan-hoad/python-icap#8]
Hello Nathan,
on many sites crashes graphics, I found the problem
ICAP Server sort query params, look

This url: http://video-tub-ru.yandex.net/i?w=200&id=62f105beb2ab4fb500437754798b42d4-00-96&h=112&n=1040 **return Error 404**

This url: http://video-tub-ru.yandex.net/i?id=62f105beb2ab4fb500437754798b42d4-00-96&n=1040&w=200&h=112 **return image** 

How to fix this problem?

UPD: Maybe replace parse_qs to parse_qsl?

**Comment by nhoad** [comment]
That HTTP server is broken, I'm not putting any effort into fixing this.

You can most likely fix this by changing the parse_qs on the query parameters to `OrderedDict(parse_qsl(url.query))`. If that works, feel free to submit a pull request.

**Comment by ghost** [comment]
I know, however, this is not a way out :) thank you. I will test
